name: Node.js CI

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 20 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Use Node.js
          uses: actions/setup-node@v3
          with: 
            node-version: "19.x"

        - name: Install dependencies
          run: npm install

        - name: Run Project
          run: npm run run
          env:
            IS_CI: 'true'
            MIN_KWH_CHARGE: ${{ vars.MIN_KWH_CHARGE }}
            FORECAST_TOLERANCE_PERCENTAGE: ${{ vars.FORECAST_TOLERANCE_PERCENTAGE }} 
            GIV_ENERGY_API_KEY: ${{ secrets.GIV_ENERGY_API_KEY }}
            SOLCAST_SITE_ID: ${{ secrets.SOLCAST_SITE_ID }}
            SOLCAST_API_KEY: ${{ secrets.SOLCAST_API_KEY }}
